apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orai-docs-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:oraichain/docs-site.git
    targetRevision: HEAD
    path: kustomize/staging
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
