apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:oraichain/docs-site.git
    targetRevision: HEAD
    path: k8s/staging
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: false