apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: docs-site
  newName: thao1996/docs-site
  newTag: e49f2535d643faaa595ffc94b65f49bae4ca146b
