name: Docker Image CI

on:
  push:
    branches: 
      - master
      # - develop
  # pull_request:
  #   branches: [ master ]

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/docs-site
        tags: ${{ github.sha }}, latest
  deploy-to-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update Kubernetes resources for staging
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
       sed -i -z -E "s/docs-site:[^\\n]+\\n/docs-site:${GITHUB_SHA}\\n/g" k8s/staging/deployment.yaml 
     
    - name: Update Kubernetes resources for prod
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
       sed -i -z -E "s/docs-site:[^\\n]+\\n/docs-site:${GITHUB_SHA}\\n/g" k8s/prod/deployment.yaml 
    - name: Commit files
      run: |
        git config --local user.email "nguyentienthao96@gmail.com"
        git config --local user.name "Thao Nguyen Tien"
        git commit -am 'chore: Delivery to prod ${{ github.event.head_commit.message }} '

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    

